dex: 
  grpc: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - auth.example.tech
    tls:
    - secretName: dex-tls
      hosts:
        - auth.example.tech
  config:
    issuer: https://auth.example.tech
    staticClients:
    - id: argo-cd
      name: Argo CD
      redirectURIs:
      - https://cluster.example.tech/auth/callback
      secret: argocd-sso-secret
    frontend: 
      issuer: Example SSO
      issuerUrl: https://example.tech
    connectors:
    - config:
        clientID: GITHUB_CLIENT_ID
        clientSecret: GITHUB_CLIENT_SECRET
        redirectURI: https://auth.example.tech/callback
        orgs:
        - name: YOUR_ORG
      id: github
      name: GitHub
      type: github
      groups: ['YOUR_ORG']
    
